---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: PruneService
metadata:
  name: prune
  namespace: openshift-prune
spec:
  managementState: Managed
  images:
    keepTagRevisions: 3
    keepTagYoungerThan: 1h0m0s
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: pod
  namespace: openshift-prune
spec:
  group: ""
  apiVersion: v1
  name: pods
  imageFieldSelectors:
  - "{.spec.initcontainers[*].image}"
  - "{.spec.containers[*].image}"
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: deploymentconfig
  namespace: openshift-prune
spec:
  group: apps.openshift.io
  apiVersion: v1
  name: deploymentconfigs
  imageFieldSelectors:
  - "{.spec.template.spec.containers[*].image}"
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: deployment
  namespace: openshift-prune
spec:
  group: extensions
  apiVersion: v1beta1
  name: deployments
  imageFieldSelectors:
  - "{.spec.template.spec.containers[*].image}"
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: replicationcontroller
  namespace: openshift-prune
spec:
  group: ""
  apiVersion: v1
  name: replicationcontrollers
  imageFieldSelectors:
  - "{.spec.template.spec.containers[*].image}"
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: daemonset
  namespace: openshift-prune
spec:
  group: extensions
  apiVersion: v1beta1
  name: daemonsets
  imageFieldSelectors:
  - "{.spec.template.spec.containers[*].image}"
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: statefulset
  namespace: openshift-prune
spec:
  group: extensions
  apiVersion: v1beta1
  name: statefulsets
  imageFieldSelectors:
  - "{.spec.template.spec.containers[*].image}"
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: replicaset
  namespace: openshift-prune
spec:
  group: extensions
  apiVersion: v1beta1
  name: replicasets
  imageFieldSelectors:
  - "{.spec.template.spec.containers[*].image}"
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: build
  namespace: openshift-prune
spec:
  group: build.openshift.io
  apiVersion: v1
  name: builds
  imageFieldSelectors:
  - "{.spec.strategy.dockerstrategy.from.name}"
  - "{.spec.strategy.sourcestrategy.from.name}"
  - "{.spec.strategy.customstrategy.from.name}"
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: buildconfig
  namespace: openshift-prune
spec:
  group: build.openshift.io
  apiVersion: v1
  name: buildconfigs
  imageFieldSelectors:
  - "{.spec.strategy.dockerstrategy.from.name}"
  - "{.spec.strategy.sourcestrategy.from.name}"
  - "{.spec.strategy.customstrategy.from.name}"
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: job
  namespace: openshift-prune
spec:
  group: batch
  apiVersion: v1
  name: jobs
  imageFieldSelectors:
  - "{.spec.template.spec.containers[*].image}"
---
apiVersion: prune.operator.openshift.io/v1alpha1
kind: ImageReference
metadata:
  name: cronjob
  namespace: openshift-prune
spec:
  group: batch
  apiVersion: v1beta1
  name: cronjobs
  imageFieldSelectors:
  - "{.spec.jobtemplate.spec.template.spec.containers[*].image}"
